var bookConfig= {
    "loadingCaption": "Loading", "loadingCaptionColor": "#000000", "loadingBackground": "#1F2232", "loadingPicture": "", "ToolbarViewMode": "Standard", "appLogoIcon": "files/extfile/appLogoIcon.png", "appLogoLinkURL": "https://obahortifruti.com.br/", "appLogoOpenWindow": "Blank", "toolbarColor": "#E8E8E8", "iconColor": "#87B04B", "iconFontColor": "#87B04B", "pageNumColor": "#111111", "formBackgroundColor": "#111111", "formFontColor": "Yes", "QRCode": "Hide", "logoHeight": 30, "logoPadding": 5, "logoTop": 5, "HomeButtonVisible": "Hide", "HomeButtonIcon": "", "AnnotationButtonVisible": "Hide", "AnnotationButtonIcon": "", "ShareButtonVisible": "Hide", "ShareButtonIcon": "Hide", "ThumbnailsButtonVisible": "Hide", "thumbnailAlpha": 70, "ThumbnailButtonIcon": "", "ZoomButtonVisible": "Show", "ZoomInButtonIcon": "", "ZoomOutButtonIcon": "", "FullscreenButtonVisible": "Show", "FullscreenButtonIcon": "", "ExitFullscreenButtonIcon": "", "TableOfContentButtonVisible": "Hide", "BookmarkButtonIcon": "Hide", "SearchButtonVisible": "Hide", "leastSearchChar": 3, "searchKeywordFontColor": "#FFB000", "SearchButtonIcon": "", "PrintButtonVisible": "Hide", "PrintButtonIcon": "", "printWatermarkFile": "Hide", "helpContentFileURL": "", "helpWidth": 400, "helpHeight": 450, "showHelpContentAtFirst": "No", "HelpButtonIcon": "", "aboutButtonVisible": "Hide", "CompanyLogoFile": "", "AboutButtonIcon": "", "AutoPlayButtonVisible": "Show", "autoPlayAutoStart": "No", "autoPlayDuration": 3, "autoPlayLoopCount": 1, "AutoPlayStartButtonIcon": "", "AutoPlayStopButtonIcon": "", "minZoomWidth": 403, "minZoomHeight": 518, "mouseWheelFlip": "yes", "DownloadButtonVisible": "Hide", "DownloadButtonIcon": "", "DownloadURL": "", "VideoButtonVisible": "Hide", "VideoButtonIcon": "", "SlideshowButtonVisible": "Hide", "SlideshowButtonIcon": "", "bgBeginColor": "#FFFFFF", "bgEndColor": "#FFFFFF", "bgMRotation": 90, "backGroundImgURL": "", "backgroundOpacity": 100, "backgroundScene": "None", "LeftShadowWidth": 50, "LeftShadowAlpha": 1, "RightShadowWidth": 30, "RightShadowAlpha": "#000000", "pageBackgroundColor": "#FFF", "flipshortcutbutton": "Show", "OriginPageIndex": 1, "HardPageEnable": "No", "RightToLeft": "No", "flippingTime": 0.5, "retainBookCenter": "Yes", "FlipStyle": "Catalog", "topMargin": 10, "bottomMargin": 10, "leftMargin": 10, "rightMargin": 10, "leftMarginOnMobile": 0, "topMarginOnMobile": 0, "rightMarginOnMobile": 0, "bottomMarginOnMobile": 0, "visibleAreaLeft": "0%", "visibleAreaTop": "0%", "visibleAreaRight": "100%", "visibleAreaBottom": "100%", "OpenWindow": "Blank", "showLinkHint": "No", "haveAdSense": "No", "adSenseLeft": 50, "adSenseTop": 50, "adSenseWidth": 200, "adSenseHeight": 200, "pageWidth": 1024, "pageHeight": 768, "language": "English", "AboutWebsite": "http://pubhtml5.com", "AboutEmail": "support@pubhtml5.com", "AboutDescription": "Pub HTML5 Demo, Generated by Pub HTML5 (MAC) - http://pubhtml5.com", "AboutAddress": "GuangZhou,GuangDong,China", "AboutMobile": "", "AboutAuthor": "Pub HTML5", "macBookVersion": "IJeVmtGPWaijEJYarqGObWqoOIaXvrCGTYiiCOZejvJPWYskCBWUvuIAVVlkDMbTsrMDXelhDKTUmsCJaYjlOMQckqBBbfmhLFUepqNJYTguEDeekrMKYUtuGLdeD788adcE_", "Html5Template": "Handy", "QRPath": "files/extfile/QRURL.png", "totalPageCount": 8, "largePageWidth": 1024, "largePageHeight": 768, "normalPath": "files/large/", "largePath": "files/large/", "thumbPath": "files/thumb/"
}

;
var fliphtml5_pages=[ {
    "l": "/../sp/1.jpg", "n": "/../sp/1.jpg", "t": "files/thumb/1.jpg"
}

,
{
    "l": "files/large/2.jpg", "n": "files/large/2.jpg", "t": "files/thumb/2.jpg"
}

,
{
    "l": "files/large/3.jpg", "n": "files/large/3.jpg", "t": "files/thumb/3.jpg"
}

,
{
    "l": "files/large/4.jpg", "n": "files/large/4.jpg", "t": "files/thumb/4.jpg"
}

,
{
    "l": "files/large/5.jpg", "n": "files/large/5.jpg", "t": "files/thumb/5.jpg"
}

,
{
    "l": "files/large/6.jpg", "n": "files/large/6.jpg", "t": "files/thumb/6.jpg"
}

,
{
    "l": "files/large/7.jpg", "n": "files/large/7.jpg", "t": "files/thumb/7.jpg"
}

,
{
    "l": "files/large/8.jpg", "n": "files/large/8.jpg", "t": "files/thumb/8.jpg"
}


];
var language=[ {
    "language": "English", "btnFirstPage": "First", "btnNextPage": "Next", "btnLastPage": "Last", "btnPrePage": "Previous", "btnGoToHome": "Home", "btnDownload": "Print", "btnThumb": "Thumbnails", "btnBookMark": "Bookmark", "frmBookMark": "Bookmark", "btnZoomIn": "Zoom In", "btnZoomOut": "Zoom Out", "btnAutoFlip": "Auto Flip", "btnStopAutoFlip": "Stop Auto Flip", "btnSocialShare": "Share", "btnHelp": "Help", "btnAbout": "About", "btnSearch": "Search", "btnFullscreen": "Fullscreen", "btnExitFullscreen": "Exit Fullscreen", "btnMore": "More", "frmPrintCaption": "Print", "frmPrintall": "Print All Pages", "frmPrintcurrent": "Print Current Page", "frmPrintRange": "Print Range", "frmPrintexample": "Example: 2,3,5-10", "frmPrintbtn": "Print", "frmShareCaption": "Share", "frmShareLabel": "Share", "frmShareInfo": "You can easily share this publication to social networks.Just click the appropriate button below", "frminsertLabel": "Insert to Site", "frminsertInfo": "Use the code below to embed this publication to your website.", "frmaboutcaption": "Contact", "frmaboutcontactinformation": "Contact Information", "frmaboutADDRESS": "Address", "frmaboutEMAIL": "Email", "frmaboutWEBSITE": "Website", "frmaboutMOBILE": "Mobile", "frmaboutAUTHOR": "Author", "frmaboutDESCRIPTION": "Description", "frmSearch": "Search", "frmToc": "Table Of Contents", "btnTableOfContent": "Table Of Contents", "btnNote": "Annotation", "lblLast": "Essa é a última página.", "lblFirst": "Essa é a primeira página.", "lblFullscreen": "Tela Inteira", "lblName": "Name", "lblPassword": "Password", "lblLogin": "Login", "lblCancel": "Cancel", "lblNoName": "User name can not be empty.", "lblNoPassword": "Password can not be empty.", "lblNoCorrectLogin": "Please enter the correct user name and password.", "btnVideo": "Video Gallery", "btnSlideShow": "Slideshow", "pnlthInputInvalid": "The search text is too short.", "btnDragToMove": "Move by mouse drag", "btnPositionToMove": "Move by mouse position", "lblHelp1": "Drag the page corner to view", "lblHelp2": "Double click to zoom in, out", "lblCopy": "Copy", "lblAddToPage": "Add To Page", "lblPage": "Page", "lblTitle": "Title", "lblEdit": "Edit", "lblDelete": "Delete", "lblRemoveAll": "Remove All", "tltCursor": "Cursor", "tltAddHighlight": "Add highlight", "tltAddTexts": "Add texts", "tltAddShapes": "Add shapes", "tltAddNotes": "Add notes", "tltAddImageFile": "Add image file", "tltAddSignature": "Add signature", "tltAddLine": "Add line", "tltAddArrow": "Add arrow", "tltAddRect": "Add rect", "tltAddEllipse": "Add ellipse", "lblDoubleClickToZoomIn": "Double click to zoom in.", "lblPages": "Pages", "infCopyToClipboard": "Your browser dose not support clipboard, please do it yourself."
}

];
var ols=[];
var flipByAudio= {}

;
var phoneNumber=[];